### ISSUE TITLE
Hey broooo, couple suggestions

### ISSUE THREAD

**Issue by JohnMaguire** [tkondrashov/Ochre#1]
don't put your api creds on github

https://github.com/tkondrashov/Ochre/blob/master/daemons/archivist.php

btw, they're stuck in git history forever. gen new keys and save them in like an env file or something. check out https://github.com/bkeepers/dotenv/tree/master/spec

also i probs wouldn't put db pass on here, even if host isn't shown. anyway whatchoo doin + also wuttup

**Comment by JohnMaguire** [comment]
o also, probs shouldn't commit `vendor/`. i'd add it to gitignore and do `composer install` when you need too. your call tho

**Comment by kladd** [comment]
Riggity riggity compromised

**Comment by tkondrashov** [comment]
ty john!!

Also I'm doing a cool idea and idk how or why you were looking at this but I'm glad you found it cause you'd think it's neat. It's an attempt to use trends to map events for journalistic purposes - ie getting firsthand tweet information about things as they happen.

http://ochre.info/ is what I have so far

**Comment by JohnMaguire** [comment]
A+ Seems pretty cool actually!
